name: Despliegue Oficial Goobi Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-official-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Verificar archivos del repositorio (Debug)
        # Lista los archivos en la consola para confirmar que docker-compose.yml está presente
        run: ls -la

      - name: Forzar descarga de la imagen oficial de Goobi Workflow
        run: docker pull docker.io/intranda/goobi-workflow:latest

      - name: Forzar descarga de la imagen oficial de MariaDB
        run: docker pull docker.io/library/mariadb:latest

      - name: Crear estructura de directorios de volúmenes
        run: |
          mkdir -p ./goobi/config \
                   ./goobi/plugins \
                   ./goobi/metadata \
                   ./goobi/lib \
                   ./logs/tomcat/workflow \
                   ./db/mysql

      - name: Desplegar infraestructura con Compose
        # El parámetro -f le indica a Docker la ruta exacta del archivo.
        # IMPORTANTE: Si guardaste tu docker-compose.yml dentro de una carpeta,
        # cambia './docker-compose.yml' por './nombre-carpeta/docker-compose.yml'
        run: docker compose -f ./docker-compose.yml up -d

      - name: Verificar el estado de los servicios
        run: docker compose ps
        
