name: Preparar Imagen OCR-D
on: 
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Imagen de Docker Hub
        run: docker pull ocrd/browser:latest

      - name: Guardar y Comprimir Imagen
        run: |
          docker save ocrd/browser:latest | gzip > ocrd_browser_latest.tar.gz

      - name: Subir como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ocrd-tarball
          path: ocrd_browser_latest.tar.gz
          retention-days: 1
  
