name: Build and Package Invenio ILS Offline Stack

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Invenio ILS Repository
        uses: actions/checkout@v4
        with:
          repository: 'inveniosoftware/invenio-app-ils'
          ref: 'v7.2.1'

      - name: Patch legacy Node.js configuration
        run: |
          echo "Aplicando diagnóstico de Rayos X..."
          
          # A: Node 16
          sed -i 's%FROM node:12%FROM node:16%g' docker/frontend/Dockerfile
          
          # B: Evitar bloqueos de red e instalaciones pesadas innecesarias
          sed -i 's%RUN npm install%RUN CYPRESS_INSTALL_BINARY=0 npm config set strict-ssl false \&\& CYPRESS_INSTALL_BINARY=0 npm install --legacy-peer-deps --silent%g' docker/frontend/Dockerfile
          
          # C: VOLCADO DIAGNÓSTICO
          # Reemplazamos la compilación por la impresión del package.json y los archivos, y forzamos el volcado.
          sed -i 's%npm run build%echo "--- PACKAGE.JSON ---" \&\& cat package.json \&\& echo "--- ARCHIVOS INTERNOS ---" \&\& ls -la \&\& exit 1%g' docker/frontend/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Invenio images
        run: |
          docker compose -f docker-compose.full.yml build
