name: Empaquetar Imágenes de InvenioILS

on:
  workflow_dispatch: # Te permite activar el empaquetado manualmente desde la pestaña Actions

jobs:
  build-tarball:
    name: Crear Paquete de Imágenes
    runs-on: ubuntu-latest

    steps:
      - name: Descargar imágenes desde Docker Hub
        run: |
          echo "Descargando servicios base pesados..."
          docker pull postgres:14
          docker pull opensearchproject/opensearch:2.11.0
          docker pull redis:7
          docker pull rabbitmq:3-management

      - name: Guardar y empaquetar en un único archivo TAR
        run: |
          echo "Empaquetando todas las imágenes en un solo archivo..."
          docker save \
            postgres:14 \
            opensearchproject/opensearch:2.11.0 \
            redis:7 \
            rabbitmq:3-management \
            -o invenio-infra.tar
          
          echo "Comprimiendo el archivo para reducir su tamaño (esto tomará un par de minutos)..."
          gzip invenio-infra.tar
          
          echo "Tamaño final del paquete:"
          du -sh invenio-infra.tar.gz

      - name: Subir archivo empaquetado a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: paquete-invenio-infra-imagenes
          path: invenio-infra.tar.gz
          retention-days: 3 # Se guardará durante 3 días para no saturar el almacenamiento de tu repositorio
