name: Descargar Modelos Bark y Tortoise

on:
  workflow_dispatch:

jobs:
  descargar_pesados:
    runs-on: ubuntu-latest
    steps:
      - name: Liberar espacio en el servidor (Obligatorio)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean

      - name: Descargar los modelos a una carpeta local
        run: |
          # Creamos la carpeta donde se guardarán los modelos
          mkdir -p ./hf_cache
          
          # Le decimos a la herramienta 'hf' que use esta carpeta como destino
          export HF_HOME=$(pwd)/hf_cache
          
          # Descargamos los modelos base de Bark con el nuevo comando
          echo "Descargando Bark..."
          hf download suno/bark
          
          # Descargamos los modelos base de Tortoise con el nuevo comando
          echo "Descargando Tortoise..."
          hf download jbetker/tortoise-tts-v2

      - name: Comprimir los modelos
        run: |
          # Usamos tar.gz para comprimir manteniendo los permisos de Linux
          tar -czf modelos-tts-cache.tar.gz ./hf_cache

      - name: Subir como artefacto para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Modelos-Voz-Pesados
          path: modelos-tts-cache.tar.gz
          retention-days: 3
